apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cr9kkadhl-python 
  janus-idp.io/tekton: cr9kkadhl-python
  backstage.io/kubernetes-id: cr9kkadhl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cr9kkadhl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml