apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cr9kkadhl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cr9kkadhl-python 
  name: cr9kkadhl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cr9kkadhl-python 
